#!/usr/bin/env python
from __future__ import print_function

import rospy
import boris_gimbal

if __name__ == '__main__':
    try:
        boris_gimbal.start_odrive()
    except rospy.ROSInterruptException:
        pass
