#!/usr/bin/env python
from __future__ import print_function

import rospy
import boris_base

if __name__ == '__main__':
    try:
        boris_base.start_odrive()
    except rospy.ROSInterruptException:
        pass
